on:
  pull_request:
  push:
    branches:
      - main
name: Python linting
permissions: {}
jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          source .venv/bin/activate
          uv pip install -U -r pyproject.toml

      - name: Python quality and format checker
        uses: konstruktoid/action-pylint@v3.0.0

